"""empty message

Revision ID: 574fe2bbc47d
Revises: 
Create Date: 2021-10-29 19:23:04.385076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574fe2bbc47d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('confirmations',
                    sa.Column('id', sa.String(50), nullable=False),
                    sa.Column("expire_at", sa.Integer(), nullable=False),
                    sa.Column("confirmed", sa.Boolean(), nullable=False),
                    sa.Column("user_id", sa.Integer(),
                              sa.ForeignKey("users.id"),  nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('password', sa.String(length=80), nullable=False),
        sa.Column('email', sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    op.create_foreign_key(None, 'confirmations', 'users', ['user_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'confirmations', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###
